초기세팅
wecode-bootcamp-korea/36-1st-Usopp-backend pull request #1
Opened 2022-08-16 08:27 UTC by Yeocb

## :: 최근 작업 주제 
- [ ] 초기세팅

<br />

## :: 구현 목표 
- 프로젝트 시작전 초기세팅

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 프로젝트 시작전 초기세팅 완료.

2022-08-16 08:29 UTC, kimjuno97 commented
.

2022-08-16 10:36 UTC, lordmyshepherd requested changes

2022-08-16 10:36 UTC, lordmyshepherd commented on routes/index.js
> +module.exports = [router];
```suggestion
module.exports = router;
```

2022-08-16 10:36 UTC, lordmyshepherd commented on routes/index.js
> +module.exports = [router];
router는 하나만 내보내지면 되기 때문에 위와 같이 수정해주세요~

2022-08-16 10:36 UTC, lordmyshepherd commented on package.json
> +    "routes": "^2.1.0",
routes는 어디서 사용하나요?

2022-08-17 01:43 UTC, kyeongraekim approved these changes
LGTM!~

2022-08-17 01:43 UTC, merged